// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("companyOrPerson")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("document")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("document")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            id = new Guid("9b747618-ea47-43b6-b43f-e94aa4b67c4e"),
                            age = 29,
                            companyOrPerson = "F",
                            createDate = new DateTime(2021, 12, 16, 20, 12, 41, 234, DateTimeKind.Local).AddTicks(4663),
                            document = "9106989784",
                            name = "Andrey Monteiro",
                            password = "masterkey",
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
